# Do not publish this crate! It is internally used for testing purposes.

[package]
name = "derive_test"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1"
proc-macro2 = "1"
amplify_syn = "1.1.6"
encoding_derive_helpers = { path = ".." }
